### PR TITLE
Unwrap pengo.handleCommand(req, res) on root POST route

### PR DESCRIPTION
**Pull request by mtso**

### CODE REVIEW

**Comment by peterjmartinson** [comment]
Can you describe why this patch is necessary?

**Comment by mtso** [comment]
This patch prepares the server to handle route modularization #9 

One solution to modularize the routes in the server is the following:
```js
// routes.js
module.exports.authController = function(req, res) { /* Slack Auth flow */ }
module.exports.renderStatic = function(_, res) { res.sendFile(__dirname + '/public'); }
```
```js
// server.js
const routes = require('./routes')
app.get('/auth', routes.authController)
app.get('/', routes.renderStatic)
app.post('/', pengo.handleCommand)
```
Each route will be passed its controllers.

The commit contained in the patch unwraps pengo's command handler and passes it directly to the route registration to match this pattern.

**Comment by peterjmartinson** [comment]
Fantastic!  Thank you for the insight.

**Review by peterjmartinson — COMMENTED** [review]
Excellent example for modularizing routes.

**Pull request merged**
